"""PySide6/QML entry point and composition root for the Hyge editor."""

from __future__ import annotations

import json
import os
import shutil
import sys
from pathlib import Path
from typing import Any

from PySide6.QtCore import QObject, Property, QUrl, Signal, Slot
from PySide6.QtQml import QQmlApplicationEngine
from PySide6.QtWidgets import QApplication
import blake3

try:
    from qml import rc_qml  # type: ignore[import-not-found]  # generated by pyside6-project
except ImportError:
    rc_qml = None

from .models import AssetGraphModel, AssetModel, AssetPreviewModel, ConsoleModel, HierarchyModel, InspectorModel, ProfilerModel
from .interaction import EditorInteractionController
from .session import EditorSession
from .viewport_item import ViewportController
from .input_controller import ViewportInputController
from .layout_state import EditorPreferences
from .theme import EditorTheme
from .e2e import EvidenceWorkflow


class EditorBridge(QObject):
    """Small QML-facing command and status facade."""

    statusChanged = Signal()
    droppedFramesChanged = Signal()
    retryChanged = Signal()

    def __init__(
        self,
        session: EditorSession,
        viewport: ViewportController,
        preferences: EditorPreferences,
        parent: QObject | None = None,
        startup_hint: str | None = None,
    ) -> None:
        super().__init__(parent)
        self._session = session
        self._viewport = viewport
        self._preferences = preferences
        self._startup_hint = startup_hint
        self._status = startup_hint or "Disconnected"
        self._retry_attempt = 0
        self._retry_delay_ms = 0
        session.stateChanged.connect(self._set_status)
        session.protocolError.connect(self._set_error)
        session.reconnectScheduled.connect(self._set_retry)
        viewport.droppedFramesChanged.connect(self.droppedFramesChanged)

    @Property(str, notify=statusChanged)
    def status(self) -> str:
        """Return the current backend connection state."""
        return self._status

    @Property(int, notify=droppedFramesChanged)
    def droppedFrames(self) -> int:
        """Return the number of dropped viewport frames."""
        return self._viewport.dropped_frames

    @Property(int, notify=retryChanged)
    def retryAttempt(self) -> int:
        """Return the current bounded reconnect attempt."""
        return self._retry_attempt

    @Property(int, notify=retryChanged)
    def retryDelayMs(self) -> int:
        """Return the delay before the next reconnect attempt."""
        return self._retry_delay_ms

    @Slot()
    def connect_backend(self) -> None:
        """Connect the session without blocking the QML thread."""
        if self._startup_hint:
            return
        self._session.connect_async()

    @Slot()
    def open_project(self) -> None:
        """Open the project selected by ``HYGE_PROJECT``."""
        self._session.open_project(os.environ.get("HYGE_PROJECT", "."))

    @Slot()
    def close_backend(self) -> None:
        """Close the backend connection."""
        self._session.close()

    @Slot()
    def retry_backend(self) -> None:
        """Retry the backend connection immediately."""
        if self._startup_hint:
            return
        self._session.retry_now()

    @Property(str, notify=statusChanged)
    def mode(self) -> str:
        """Return the local editor mode label."""
        return self._preferences.mode

    def _set_status(self, state: str) -> None:
        self._status = state.capitalize()
        self.statusChanged.emit()

    def _set_retry(self, attempt: int, delay_ms: int) -> None:
        self._retry_attempt = attempt
        self._retry_delay_ms = delay_ms
        self.retryChanged.emit()

    def _set_error(self, message: str) -> None:
        self._status = f"Error: {message}"
        self.statusChanged.emit()


def create_application(
    argv: list[str] | None = None,
    session: EditorSession | None = None,
    user_data: Path | None = None,
) -> tuple[QApplication, QQmlApplicationEngine, EditorSession, ViewportController]:
    """Create a source-checkout shell suitable for production or tests."""
    app = QApplication.instance() or QApplication(argv if argv is not None else sys.argv)
    default_user_data = Path(sys.executable).resolve().parent / "user_data"
    if not (getattr(sys, "frozen", False) or "__compiled__" in globals()):
        default_user_data = Path.cwd() / "user_data"
    preferences = EditorPreferences(user_data or Path(os.environ.get("HYGE_USER_DATA", default_user_data)))
    theme = EditorTheme(preferences, app)
    theme.apply()
    address = os.environ.get("HYGE_EDITOR_ADDRESS")
    packaged_without_backend = "__compiled__" in globals() and not address
    backend = session or EditorSession(
        address or "127.0.0.1:3765",
        os.environ.get("HYGE_EDITOR_TOKEN", "hyge-local-dev"),
    )
    viewport = ViewportController(backend)
    engine = QQmlApplicationEngine()
    boot_log = os.environ.get("HYGE_EDITOR_BOOT_LOG")
    if boot_log:
        def record_qml_warnings(warnings: list[Any]) -> None:
            Path(boot_log).write_text(
                "\n".join(str(warning) for warning in warnings),
                encoding="utf-8",
            )

        engine.warnings.connect(record_qml_warnings)
    engine.addImageProvider("hyge-viewport", viewport.provider)
    startup_hint = "Launch HygeEditor.cmd" if packaged_without_backend else None
    bridge = EditorBridge(backend, viewport, preferences, engine, startup_hint=startup_hint)
    interaction = EditorInteractionController(backend, engine)
    viewport_input = ViewportInputController(backend, viewport, engine)
    hierarchy = HierarchyModel(interaction, engine)
    inspector = InspectorModel(interaction, engine)
    assets = AssetModel(interaction, backend, engine)
    asset_graph = AssetGraphModel(engine)
    preview = AssetPreviewModel(backend, engine)
    console = ConsoleModel(backend, engine)
    profiler = ProfilerModel(engine)
    backend.worldSnapshot.connect(hierarchy.update_snapshot)
    backend.worldSnapshot.connect(inspector.update_snapshot)
    backend.selectionChanged.connect(hierarchy.update_selection)
    backend.selectionChanged.connect(inspector.update_selection)
    interaction.conflictFieldChanged.connect(inspector.set_conflict)
    backend.assetSnapshot.connect(assets.update_snapshot)
    backend.assetSnapshot.connect(asset_graph.update_snapshot)
    backend.consoleSnapshot.connect(console.update_snapshot)
    backend.profilerSnapshot.connect(profiler.update_snapshot)
    def prime_frontend(_handshake: Any) -> None:
        backend.open_project(os.environ.get("HYGE_PROJECT", "."))
        scene = os.environ.get("HYGE_SCENE")
        if scene:
            backend.open_scene(scene)
        backend.request("request_asset_snapshot")
        backend.request("request_console_snapshot")
        backend.request("request_profiler_snapshot")
        backend.request("open_viewport_transport")

    backend.connected.connect(prime_frontend)
    root = engine.rootContext()
    root.setContextProperty("editorBridge", bridge)
    root.setContextProperty("editorPreferences", preferences)
    root.setContextProperty("editorTheme", theme)
    root.setContextProperty("editorInteraction", interaction)
    root.setContextProperty("hierarchyModel", hierarchy)
    root.setContextProperty("inspectorModel", inspector)
    root.setContextProperty("assetModel", assets)
    root.setContextProperty("assetGraphModel", asset_graph)
    root.setContextProperty("assetPreviewModel", preview)
    root.setContextProperty("consoleModel", console)
    root.setContextProperty("profilerModel", profiler)
    root.setContextProperty("viewportController", viewport)
    root.setContextProperty("viewportInput", viewport_input)
    if rc_qml is not None:
        engine.load(QUrl("qrc:/qml/Main.qml"))
    if not engine.rootObjects():
        if getattr(sys, "frozen", False) or "__compiled__" in globals():
            frozen_roots = [
                Path(os.environ["HYGE_EDITOR_PACKAGE_DIR"]).resolve()
                if os.environ.get("HYGE_EDITOR_PACKAGE_DIR")
                else Path(sys.argv[0]).resolve().parent,
                Path(sys.argv[0]).resolve().parent,
                Path(sys.executable).resolve().parent,
                Path(__file__).resolve().parent,
            ]
            qml_path = next(
                (root / "qml" / "Main.qml" for root in frozen_roots if (root / "qml" / "Main.qml").is_file()),
                frozen_roots[0] / "qml" / "Main.qml",
            )
        else:
            qml_path = Path(__file__).parents[2] / "qml" / "Main.qml"
        engine.load(QUrl.fromLocalFile(str(qml_path)))
    if boot_log and not engine.rootObjects():
        with Path(boot_log).open("a", encoding="utf-8") as log:
            log.write("\nrootObjects=0\n")
    app.aboutToQuit.connect(backend.close)
    app.aboutToQuit.connect(viewport.close)
    app.aboutToQuit.connect(viewport_input.clear_transient)
    app.aboutToQuit.connect(preferences.save)
    return app, engine, backend, viewport


def capture_evidence(
    app: QApplication,
    engine: QQmlApplicationEngine,
    viewport: ViewportController,
    evidence_dir: Path,
) -> None:
    """Capture shell, viewport and persisted-scene evidence for an E2E run."""
    evidence_dir.mkdir(parents=True, exist_ok=True)
    roots = engine.rootObjects()
    shell_output = evidence_dir / "editor.png"
    shell_saved = shell_output.is_file() and shell_output.stat().st_size > 8
    if roots and not shell_saved:
        shell_image = roots[0].grabWindow()
        shell_saved = not shell_image.isNull() and shell_image.save(
            str(shell_output), "PNG"
        )
    viewport_output = evidence_dir / "viewport.png"
    viewport_saved = viewport_output.is_file() and viewport_output.stat().st_size > 8
    if not viewport_saved:
        viewport_saved = viewport.save_png(str(viewport_output))
    scene = os.environ.get("HYGE_SCENE")
    saved_output = evidence_dir / "saved.hyge-world"
    if scene and Path(scene).is_file() and not saved_output.exists():
        shutil.copy2(scene, saved_output)
    saved_scene = saved_output.is_file()
    workflow_path = evidence_dir / "workflow.json"
    workflow_success = False
    if workflow_path.is_file():
        workflow_success = bool(json.loads(workflow_path.read_text(encoding="utf-8")).get("success"))
    workflow = {}
    if workflow_path.is_file():
        workflow = json.loads(workflow_path.read_text(encoding="utf-8"))
    evidence_files = [shell_output, viewport_output, saved_output]
    hashes = {
        path.name: blake3.blake3(path.read_bytes()).hexdigest()
        for path in evidence_files if path.is_file()
    }
    (evidence_dir / "manifest.json").write_text(
        json.dumps(
            {
                "editor_png": shell_saved,
                "viewport_png": viewport_saved,
                "saved_scene": saved_scene,
                "workflow_success": workflow_success,
                "viewport_width": viewport.provider._image.width(),
                "viewport_height": viewport.provider._image.height(),
                "scene_revision": viewport.last_scene_revision,
                "camera_revision": viewport.last_camera_revision,
                "entity": workflow.get("entity"),
                "scene_node_id": workflow.get("scene_id"),
                "assertions": {
                    "workflow": workflow_success,
                    "persist_on_reload": workflow.get("reload_translation") == [3.0, 1.0, 0.0],
                },
                "hash_algorithm": "blake3",
                "hashes": hashes,
            },
            indent=2,
        ),
        encoding="utf-8",
    )


def main() -> int:
    """Start the Qt application and connect it to the Rust service."""
    app, engine, session, viewport = create_application()
    if not engine.rootObjects():
        session.close()
        return 1
    evidence = os.environ.get("HYGE_EDITOR_EVIDENCE_DIR")
    if evidence:
        evidence_dir = Path(evidence)
        evidence_dir.mkdir(parents=True, exist_ok=True)
        session.enable_trace(str(evidence_dir / "protocol.jsonl"))
        app.aboutToQuit.connect(lambda: capture_evidence(app, engine, viewport, evidence_dir))
        if os.environ.get("HYGE_EDITOR_E2E") == "1":
            scene = Path(os.environ["HYGE_SCENE"])
            external = Path(os.environ["HYGE_EDITOR_EXTERNAL_SCENE"])
            workflow = EvidenceWorkflow(
                app,
                session,
                engine.rootContext().contextProperty("editorInteraction"),
                viewport,
                scene,
                external,
                evidence_dir,
                lambda: capture_evidence(app, engine, viewport, evidence_dir),
                engine,
            )
            engine.setProperty("r103EvidenceWorkflow", workflow)
    if not ("__compiled__" in globals() and not os.environ.get("HYGE_EDITOR_ADDRESS")):
        session.connect_async()
    return app.exec()


if __name__ == "__main__":
    raise SystemExit(main())
